import type { Metadata } from "next";
import "./globals.css";
import CompHeader from "./components/CompHeader/CompHeader";
import CompDarkMode from "./components/CompDarkMode/CompDarkMode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light" suppressHydrationWarning>
      <body className="transition-colors duration-200">
        <CompHeader />
        {children}
      </body>
    </html>
  );
}
