import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kaue Samartino Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="light" suppressHydrationWarning>
      <body className="transition-colors duration-200">
        {children}
      </body>
    </html>
  );
}
