import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Layout/Header";
import InteractiveBackground from "./components/InteractiveBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light" suppressHydrationWarning>
      <body className="transition-colors duration-200">
        <InteractiveBackground />
        <Header />
        <div style={{ position: "relative", zIndex: 1 }}>{children}</div>
      </body>
    </html>
  );
}
